version: "3.9"
services:
    postgres:
        image: postgres:14.4
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
