name: Validations

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            - name: "CD to Backend"
              run: cd ./backend

            - name: Install Dependencies
              run: npm install

            - name: Run tests
              run: npm run test

            - name: Builds
              run: npm run build
